//! Best-effort detection of "sensitive" clipboard content (passwords, etc.) so
//! secrets aren't written into the history. Honors the de-facto OS conventions:
//!   - macOS: `org.nspasteboard.ConcealedType` / `TransientType` / `AutoGeneratedType`
//!   - Windows: the `ExcludeClipboardContentFromMonitorProcessing` format
//! Returns false where unsupported.

#[cfg(target_os = "macos")]
pub fn is_sensitive() -> bool {
    use objc2_app_kit::NSPasteboard;
    objc2::rc::autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let Some(types) = pasteboard.types() else {
            return false;
        };
        for i in 0..types.count() {
            let t = types.objectAtIndex(i);
            let name = t.to_string();
            if name == "org.nspasteboard.ConcealedType"
                || name == "org.nspasteboard.TransientType"
                || name == "org.nspasteboard.AutoGeneratedType"
            {
                return true;
            }
        }
        false
    })
}

#[cfg(target_os = "windows")]
pub fn is_sensitive() -> bool {
    use windows_sys::Win32::System::DataExchange::{
        IsClipboardFormatAvailable, RegisterClipboardFormatW,
    };
    unsafe {
        let name: Vec<u16> = "ExcludeClipboardContentFromMonitorProcessing"
            .encode_utf16()
            .chain(std::iter::once(0))
            .collect();
        let format = RegisterClipboardFormatW(name.as_ptr());
        format != 0 && IsClipboardFormatAvailable(format) != 0
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
pub fn is_sensitive() -> bool {
    false
}
